name: build & deploy (frontend)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME: docker.io/${{ secrets.DH_USER }}/web-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 한국 시간 기준 태그 (예: 0821_1812)
      - name: Set IMAGE_TAG with datetime (KST)
        run: |
          echo "TZ=Asia/Seoul" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(date +'%m%d_%H%M')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_PASS }}

      # Buildx + 레이어 캐시로 도커 빌드 가속
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push image (with cache)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy container image to App Service
        run: |
          az webapp config container set \
            --name ${{ secrets.WEBAPP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --docker-custom-image-name $IMAGE_NAME:$IMAGE_TAG \
            --docker-registry-server-url https://index.docker.io

      - name: Restart App
        run: az webapp restart --name ${{ secrets.WEBAPP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }}

      - name: Show App URL
        run: az webapp show --name ${{ secrets.WEBAPP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query defaultHostName -o tsv
